### PR TITLE
APP-957 Update Universal integration README to reflect new rendering pipeline

### PR DESCRIPTION
**Pull request by robson-sanchez**

### CODE REVIEW

**Comment by pdarde-daitan** [comment]
Change "The team is working on **a** integration-provisioning..." for " The team is working on **an** integration-provisioning..."

**Comment by pdarde-daitan** [comment]
Would be nice if we had a hyperlink for the e-mail contact in the "... please contact [Symphony Support](https://www.symphony.com) to get your configuration and bot id's."

**Comment by pdarde-daitan** [comment]
Is that right? "...For the application context, you should always **user** app/ provided in the env.sh."

**Comment by pdarde-daitan** [comment]
Would be nice if we had hyperlinks for that:

JDK 1.8
Maven 3.0.5+
Node 6.10
Gulp (globally installed)
Webpack (globally installed)

for instance:

[JDK 1.8](http://www.oracle.com/technetwork/java/javase/downloads/jdk8-downloads-2133151.html)
[Maven 3.0.5+](https://maven.apache.org/download.cgi)
[Node 6.10](https://nodejs.org/en/)
[Gulp](http://gulpjs.com/) (globally installed)
[Webpack](https://webpack.github.io/) (globally installed)

**Comment by robson-sanchez** [comment]
ok to test

**Review by ecarrenho-daitan — APPROVED** [review]
LGTM

**Pull request merged**
